# -*- coding: utf-8 -*-
"""
This code is used to select the stars whose VM (Visual Magnitude) is less than 
the VM_thre (Visual Magnitude Threshold).

Note that for data accuracy, the angles in file 'sao' & 'sao_VM_thre.txt' have 
the unit of rad. The RA(RightAscension) & Dec(Declination) also have the unit 
of rad. Other angles all have the unit of deg.

Revised in 1/27/2020
by YouZhiyuan
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


# CN: CatalogNumber
# VM: VisualMagnitude
# RA: RightAscension
# Dec:  Declination
# vx,vy,vz: unit vector generated by RA & Dec or pixel coordinate
# _thre: threshold


def convert_SAO_to_txt(f_read_name, f_save_name, VM_thre, visualization=True):
    # VM_thre: Visual Magnitude Threshold
    with open(f_read_name) as fr:
        lines = fr.readlines()

    # save the selected stars in SAO
    # format:
    # CN, VM, RA, Dec
    with open(f_save_name, "w") as fw:
        # select the stars whose VM is less than VM_thre
        CN_list = []
        VM_list = []
        RA_list = []
        Dec_list = []
        for line in lines:
            # line: len(line) = 205, line[204] = '\n'
            CN = line[0:6]
            VM = line[80:84]
            RA = line[183:193]
            Dec = line[193:204]
            if float(VM) < VM_thre:
                fw.write(f"{CN} {VM} {RA} {Dec}\n")
                CN_list.append(CN)
                VM_list.append(VM)
                RA_list.append(RA)
                Dec_list.append(Dec)

    if visualization:
        # calculate the unit vector of every selected star
        vz_list = np.sin(np.float32(Dec_list))
        vx_list = np.cos(np.float32(RA_list)) * np.cos(np.float32(Dec_list))
        vy_list = np.sin(np.float32(RA_list)) * np.cos(np.float32(Dec_list))

        # draw the picture to show the SAO
        fig = plt.figure()
        ax = Axes3D(fig)
        ax.scatter(0, 0, 0, s=10, c="r")
        ax.scatter(vx_list, vy_list, vz_list, s=4, c="b", alpha=0.4)
        ax.set_title(f"SAO star catalog with visual magnitude less than {VM_thre}")
        ax.set_zlabel("Z", fontdict={"size": 15, "color": "red"})
        ax.set_ylabel("Y", fontdict={"size": 15, "color": "red"})
        ax.set_xlabel("X", fontdict={"size": 15, "color": "red"})
        plt.show()


if __name__ == "__main__":
    VM_thre = 6.0  # Visual Magnitude Threshold
    f_read_name = "database/sao"
    f_save_name = f"database/sao_VM_thre{VM_thre}.txt"

    convert_SAO_to_txt(f_read_name, f_save_name, VM_thre)
